[package]
name = "tess"
version = "0.7.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "tess"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.1.1", features = ["api-all"] }
portable-pty = "0.7.0"
infer = "0.12.0"
notify = "5.1.0"
tokio = "1.25.0"
dirs-next = "2.0.0"
uuid = "1.3.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = true
lto = true
codegen-units = 1
